SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MOVE_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_DEATH_TIMER = 2
PLAYER_I_SECONDS = 1

SHOT_RADIUS = 5
SHOT_COOLDOWN = 0.3

PARTICLE_COUNT = 12
PARTICLE_RADIUS = 5