SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MOVE_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_DEATH_TIMER = 2

SHOT_RADIUS = 5
SHOT_COOLDOWN = 0.3

PARTICLE_COUNT = 12
PARTICLE_RADIUS = 5

SHIELD_DURATION = 1
FIRE_RATE_DURATION = 5
SPEED_DURATION = 10
POWERUP_RADIUS = 10
SPEED_MIN_SPEED = 50
SPEED_VEL = 0.15